# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing_db
    volumes:
      - /srv/incit-ev/dss/mongo/data:/data/db

  mongo-seed-defaults:
    build: ./mongo-seed/seed-defaults
    depends_on:
      - mongo

  mongo-seed-users:
    build: ./mongo-seed/seed-users
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: testing_db
      ME_CONFIG_MONGODB_SERVER: mongodb

  dss:
    build: ../ #dss-api:3.0.0   image name for testing API
    #image: ghcr.io/links-fcc/dss-api:2.8.0
    container_name: dss
    ports:
      - 5000:80
    environment:
      MONGO_URI: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: testing_db
      SIMULATOR_URI: http://dss-integration-0:80/api/v1/simulations/
      DATABASE_NAME: incitev
      DSS_PRIVATE_KEY: /app/dss-api.key
      DSS_PUBLIC_KEY: /app/dss-api.key.pub
    volumes:
      - ./dss-api.key:/app/dss-api.key:ro
      - ./dss-api.key.pub:/app/dss-api.key.pub:ro
    depends_on:
      dss-integration-0:
        condition: service_healthy
      dss-integration-1:
        condition: service_healthy
      dss-integration-2:
        condition: service_healthy
      dss-integration-3:
        condition: service_healthy

  dss-integration-0:
    #build: ghcr.io/links-fcc/integration
    image: ghcr.io/links-fcc/integration:2.8.0
    container_name: dss-integration-0
    ports:
      - 9000:80
    environment:
      DSS_URI: dss
      DSS_USER: dss-integration
      DSS_PASSWORD: Simulator!2022!
      DSS_PUBLIC_KEY: /app/dss-api.key.pub
    volumes:
      - ./dss-api.key.pub:/app/dss-api.key.pub:ro
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80", "-o", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  dss-integration-1:
    #build: ghcr.io/links-fcc/integration
    image: ghcr.io/links-fcc/integration:2.8.0
    container_name: dss-integration-1
    ports:
      - 9001:80
    environment:
      DSS_URI: dss
      DSS_USER: dss-integration
      DSS_PASSWORD: Simulator!2022!
      DSS_PUBLIC_KEY: /app/dss-api.key.pub
    volumes:
      - ./dss-api.key.pub:/app/dss-api.key.pub:ro
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80", "-o", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  dss-integration-2:
    #build: ghcr.io/links-fcc/integration
    image: ghcr.io/links-fcc/integration:2.8.0
    container_name: dss-integration-2
    ports:
      - 9002:80
    environment:
      DSS_URI: dss
      DSS_USER: dss-integration
      DSS_PASSWORD: Simulator!2022!
      DSS_PUBLIC_KEY: /app/dss-api.key.pub
    volumes:
      - ./dss-api.key.pub:/app/dss-api.key.pub:ro
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80", "-o", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  dss-integration-3:
    #build: ghcr.io/links-fcc/integration
    image: ghcr.io/links-fcc/integration:2.8.0
    container_name: dss-integration-3
    ports:
      - 9003:80
    environment:
      DSS_URI: dss
      DSS_USER: dss-integration
      DSS_PASSWORD: Simulator!2022!
      DSS_PUBLIC_KEY: /app/dss-api.key.pub
    volumes:
      - ./dss-api.key.pub:/app/dss-api.key.pub:ro
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80", "-o", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  dss-frontend:
    image: ghcr.io/atos-research-and-innovation/incitev-dss-frontend:latest
    container_name: dss-frontend
    ports:
      - 3000:3000
    environment:
      DSS_BACKEND_BASE_URL: http://dss:80/
      NEXTAUTH_URL: http://localhost:3000/
      NEXTAUTH_SECRET: vibwarwvuncx4fyvb7nctfhgcbnnsx79387d9gv754ncxyh7fqhjd27v53q8cn
